### ISSUE TITLE
Hyphenate intro text on mobile

### ISSUE THREAD

**Issue by miketully** [miketully/miketully.github.io#1]
![img_6632](https://cloud.githubusercontent.com/assets/3248472/26701383/e2ca9274-46ee-11e7-84f5-5797dbe0407b.PNG)

Can we hyphenate this text on mobile only?

**Comment by tylermadsen** [comment]
How's this looking @miketully ?

**Comment by miketully** [comment]
On second thought, let's keep this the way it was, without hyphenation please.

**Comment by tylermadsen** [comment]
No problem 👌
