### ISSUE TITLE
Change 'Clients' column width to allow for no line breaks

### ISSUE THREAD

**Issue by miketully** [miketully/miketully.github.io#2]
![image](https://cloud.githubusercontent.com/assets/3248472/26701415/062d2f24-46ef-11e7-8e7a-6b9be7f8c7a2.png)

Please change the Clients column width (or space btw 'clients' and 'elsewhere') to allow for no line breaks in 'clients'.

**Comment by miketully** [comment]
Line break examples including: 'Cooper Hewitt...' ' Lincoln Center...'

**Comment by tylermadsen** [comment]
How's this looking now @miketully ?

**Comment by miketully** [comment]
Looks good!
