### ISSUE TITLE
Increase intro paragraph line-height

### ISSUE THREAD

**Issue by miketully** [miketully/miketully.github.io#3]
![image](https://cloud.githubusercontent.com/assets/3248472/26701492/5ba5e824-46ef-11e7-9e9e-b5582794f33a.png)

Please increase intro paragraph line height by 1px/pt.

**Comment by tylermadsen** [comment]
How's this look @miketully ?

**Comment by miketully** [comment]
Cam we increase line-height by 1pt more?

**Comment by tylermadsen** [comment]
Increased
