### ISSUE TITLE
Add 'programmed by' credit for yourself

### ISSUE THREAD

**Issue by miketully** [miketully/miketully.github.io#4]
![image](https://cloud.githubusercontent.com/assets/3248472/26701594/bbec9c78-46ef-11e7-9302-65430566f09b.png)

Tyler, in this category will you add this (if you're okay with that of course):
'Site programmed
by Tyler Madsen'

Specifically line-broken like that and linking your name to whichever site you might like to link to if you want.

**Comment by miketully** [comment]
Definitely okay to hyperlink (or not) to your name — up to you so I'm okay with either.

NP to add my name and thanks for doing so. Could we do a line-break to bring '& Mike Tully' on to the next line? So it reads:

Typeset in Brando
by Mike Abbink
Site programmed
by Tyler Madsen 
& Mike Tully
Updated on 6 . 7 . 2017
The time is 11:54 AM
© 2017 — Mike Tully

**Comment by tylermadsen** [comment]
Added that linebreak
